version: "3.8"

services:
  app:
    image: thewca/wca-live
    restart: always
    environment:
      - HOST
      - DATABASE_URL
      - SECRET_KEY_BASE
      - WCA_HOST
      - WCA_OAUTH_CLIENT_ID
      - WCA_OAUTH_CLIENT_SECRET
    volumes:
      # Persist cache data (like regional records)
      - app-tmp:/app/tmp
    ports:
      - "4000:4000"
    logging:
      driver: json-file
      options:
        # Note: by default Docker doesn't impose any limits on logs storage
        max-file: "10"
        max-size: "10m"
volumes:
  app-tmp:
