FROM hexpm/elixir:1.14.2-erlang-25.1.2-alpine-3.14.8

# Install node
RUN apk add nodejs npm

# Install dependencies
RUN apk add --no-cache \
    # build
    build-base git python3 \
    # runtime
    openssl ncurses-libs \
    # PDF generation
    ttf-freefont wkhtmltopdf

ENV HOME=/home/app
# Create home dir explicitly, in case someone runs with `--user`
RUN mkdir $HOME && chmod 777 $HOME

# Install hex and rebar
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app

CMD [ "sh", "-c", "mix setup; mix phx.server" ]
