FROM hexpm/elixir:1.12.3-erlang-24.1.6-alpine-3.14.2

# Install dependencies.
RUN apk add --no-cache \
    # build
    build-base git python3 \
    # runtime
    openssl ncurses-libs \
    # PDF generation
    ttf-freefont wkhtmltopdf

# Install hex and rebar.
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /server

CMD [ "sh", "-c", "mix setup; mix phx.server" ]
