FROM hexpm/elixir:1.11.4-erlang-23.3.4-alpine-3.13.3

# Install dependencies.
RUN apk add --no-cache \
    # build
    build-base git python \
    # runtime
    openssl ncurses-libs \
    # PDF generation
    ttf-ubuntu-font-family wkhtmltopdf

# Install hex and rebar.
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /server

CMD [ "sh", "-c", "mix setup; mix phx.server" ]
